makandra/active_type

lib/active_type/type_caster.rb
Rails 4.2.0 with pg 0.18.1 delegates to the database to look up data types. The database doesn't recognize Rails-style datatypes like `:string`; it expects native types like `varchar`.
The patch translates the Rails type to the PG type using the `native_database_types` lookup table that the PG adapter provides.
Should fix #19.
=> Use native database type for type casting in pg

lib/active_type/no_table.rb
I tried the gem on our existing Rails 4.0.0 project. 
After incorporating it into the project, I started a rails console and tried to make a new object using the following code:
class SignIn < ActiveType::Object
attribute :email, :string
attribute :nickname, :string, default: proc { email.split('@').first }
end
SignIn.new(email: "tobias@example.org")
---
This returned the following error: 
TypeError: can't dup NilClass
from /Users/dave/.rvm/gems/ruby-2.0.0-p594/gems/activerecord-4.0.0/lib/active_record/core.rb:185:in `dup'
When I went into core.rb I found the problem. In version 4.0.0 dup method is being called on column_types variable. The problem is that column_types is nil. So basically calling column_types.dup throws an exception. 
I went through Rails 4.1 and 4.2. There wouldn't a …
=> Making the gem to work with Rails version 4.0.0

lib/active_type/type_caster.rb, spec/active_type/object_spec.rb
Don't try to look up unknown data types via the db adapter. Instead, we will silently ignore such data types.
=> [fixes #25] dont crash for database types without casting rules

CHANGELOG.md
This PR adds a CHANGELOG, as suggested in #27.
The format of the change log is loosely based on the recommendations from [keepachangelog.com](http://keepachangelog.com).
=> Add a CHANGELOG (going back to v0.3.0)

.travis.yml, gemfiles/Gemfile.4.2.1.mysql2, gemfiles/Gemfile.4.2.1.mysql2.lock, lib/active_type/type_caster.rb, spec/support/database.rb
I encountered some problems when using boolean attributes with a mysql2 database adapter. Seemed to be because:
ActiveRecord::Base.connection.native_database_types[:boolean][:name]
#=> "tinyint"
and this was causing it to cast values to/from tinyint values (Fixnum) rather than to/from booleans.
I've stopped it from looking up `native_database_type` for booleans, and this seems to have fixed it. Also attempted to cover mysql2 in the tests (works locally, we'll see whether it works with travis...).
=> Don't type cast mysql boolean as tinyint. Hopefully fixes #42 and #46.

lib/active_type/no_table.rb, spec/active_type/object_spec.rb, spec/spec_helper.rb
Fixes #47.
In order to test an `after_commit` hook, the test can't be run within a transaction wrapper, which by default is being applied to all RSpec examples. To work around this, I added a `:rollback => false` RSpec metadata to disable the wrapper on a per-example basis.
For ActiveType::Object, it is OK to commit the transaction, because there is no backing table that will affected.
=> Fix after_commit callbacks for ActiveType::Object on Rails 4

README.md
Fixed hash/array brackets in README's example
=> Fixed hash/array brackets in README's example

lib/active_type/virtual_attributes.rb
```ruby
class SignUp < ActiveType::Record[User]
end
SignIn.new().dup # raise error "can't dup NilClass"
```
=> Fix bug 'can't dup NilClass', when ActiveType::Object has no attributes

lib/active_type/no_table.rb, lib/active_type/virtual_attributes.rb, spec/active_type/object_spec.rb, spec/active_type/record_spec.rb
When I'm debugging I find it convenient to use the inspect method on objects. Currently only the object name is returned for active_type objects. This code is based on ActiveRecord and it returns names and values of attributes.
I've only started using active_type recently so I might have put the code in the wrong place or something like that.
Thanks!
=> make inspect method return more useful information

lib/active_type/util.rb
FIX: when casting ActiveRecord instance to ActiveType::Record, set ActiveModel::Errors instance variable @base to the ActiveType::Record instance
=> FIX: make errors.add work when inheriting from ActiveType::Record

lib/active_type.rb, spec/spec_helper.rb, spec/support/database.rb
When active_type is used inside Rails it loads `ActiveRecord::Base` too early. This causes configuration settings set via `Rails.application.config.active_record` (for example `Rails.application.config.belongs_to_required_by_default = true`) set in a Rails initializer (as is default in Rails 5) to be disregarded.
In case `ActiveType` is used without `Rails`, we should load regularly.
=> Fix AR config issues [fixes #72]

.gitignore, .travis.yml, Rakefile, gemfiles/Gemfile.3.2.mysql2, gemfiles/Gemfile.3.2.mysql2.lock, gemfiles/Gemfile.3.2.sqlite3, gemfiles/Gemfile.3.2.sqlite3.lock, gemfiles/Gemfile.4.0.sqlite3, gemfiles/Gemfile.4.0.sqlite3.lock, gemfiles/Gemfile.4.1.sqlite3, gemfiles/Gemfile.4.1.sqlite3.lock, gemfiles/Gemfile.4.2.1.mysql2, gemfiles/Gemfile.4.2.1.mysql2.lock, gemfiles/Gemfile.4.2.1.pg, gemfiles/Gemfile.4.2.1.pg.lock, gemfiles/Gemfile.4.2.1.sqlite3, gemfiles/Gemfile.4.2.1.sqlite3.lock, gemfiles/Gemfile.5.0.0.mysql2, gemfiles/Gemfile.5.0.0.mysql2.lock, gemfiles/Gemfile.5.0.0.pg, gemfiles/Gemfile.5.0.0.pg.lock, gemfiles/Gemfile.5.0.0.sqlite3, gemfiles/Gemfile.5.0.0.sqlite3.lock, lib/active_type.rb, spec/isolated/load_without_active_record_use_spec.rb, spec/isolated/load_without_active_record_use_within_rails_spec.rb, spec/isolated/require_does_not_trigger_ar_load_spec.rb, spec/isolated_spec_helper.rb
#73 introduced a regression as demonstrated in #75.
Instead of using `ActiveRecord`'s load hook, just use regular Ruby autoloading.
I've added specs to test #73 and these changes, which have to run in isolation from other specs. These will run when using `rake spec` or `rake all:spec` or travis.
=> use autoloading

lib/active_type/type_caster.rb
At least when running in production under passenger, without this, our app leaks a database connection for each passenger instance.  The connection is only used during initialization of the stack and then sits idle forever.
=> wrap activerecord call in a with_connection block so we don't leak a db connection

gemfiles/Gemfile.3.2.mysql2.lock, gemfiles/Gemfile.3.2.sqlite3.lock, gemfiles/Gemfile.4.0.sqlite3.lock, gemfiles/Gemfile.4.1.sqlite3.lock, gemfiles/Gemfile.4.2.1.mysql2.lock, gemfiles/Gemfile.4.2.1.pg.lock, gemfiles/Gemfile.4.2.1.sqlite3.lock, gemfiles/Gemfile.5.0.0.mysql2.lock, gemfiles/Gemfile.5.0.0.pg.lock, gemfiles/Gemfile.5.0.0.sqlite3.lock, lib/active_type/nested_attributes/association.rb, lib/active_type/type_caster.rb, lib/active_type/virtual_attributes.rb, spec/isolated/active_object_does_not_need_db_spec.rb
I've tried to change the type casting logic to not require a database connection. This is probably a breaking change for Rails 4 and 5, since it means no support for database-specific types, but I never actually used this. I don't feel this has been a useful (or in the case of `ActiveType::Object` expected) feature, so I think this should be worth it?
@triskweline: Do you have a opinion on this?
=> make ActiveType::Object work without db connection

lib/active_type/nested_attributes/nests_many_association.rb, lib/active_type/nested_attributes/nests_one_association.rb, spec/active_type/nested_attributes_spec.rb, spec/support/database.rb
In Rails 5, it is convenient to set uuid as the id for models. However, the current implementation of this gem assumes that the type of id will always be an integer. In my opinion, I think that using string instead of integer will be more general, so I create this PR to show my suggested changes, hoping that we can have some discuss on this if necessary :)
=> Support uuid for nest association

lib/active_type/record_extension/inheritance.rb, spec/active_type/extended_record/single_table_inheritance_spec.rb
If we don't override descends_from_active_record? , then SQL queries will include a
WHERE type in ('DerivedClassName')
which is not what we want
=> Don't add type conditions when inheriting a base STI type

lib/active_type/record_extension/inheritance.rb, spec/active_type/change_association_spec.rb, spec/support/database.rb
When using `change_assocation` with a [polymorphic association](https://guides.rubyonrails.org/association_basics.html#polymorphic-associations), active type is overwriting the association's `foreign_key`, causing "unknown column" errors.
Fix this by skipping the foreign key override when using a polymorphic association (`as: ...`).
=> Fix change_association with polymorphic association

CHANGELOG.md, lib/active_type/nested_attributes/nests_one_association.rb
New nests_one records are now built with the passed in attributes instead of an empty hash. Fixes #119
=> Fix nests_one association record building

lib/active_type/record_extension/inheritance.rb, spec/active_type/record_extension_spec.rb
This allows creating translations for the derived classes themselves instead of polluting
the base class translations
Fixes: #115
=> Override i18n_key on ActiveRecord-derived classes

.github/workflows/test.yml, lib/active_type/virtual_attributes.rb, spec/integration/sign_in_spec.rb, spec/integration/sign_up_spec.rb, spec/shared_examples/serialization.rb
This implements YAML serialization in a way that's (hopefully) completely compatible with ActiveRecord's current and previous implementation. Closes #127
=> Implement YAML serialization

lib/active_type/nested_attributes/association.rb
Refactor ActiveType::NestedAttributes::Association#validate to comply with ActiveModel::Error API. Fixes #131
=> conform with ActiveModel::Errors API

lib/active_type/util.rb
This PR adds `@mutations_from_database` instance variable copy to `ActiveType.cast_record` method. It's needed because [change method from ActiveSupport](https://github.com/rails/rails/blob/main/activemodel/lib/active_model/dirty.rb#L225) uses this instance variable to carefully handle model changes. 
F.e. now I have a situation when [model setter is overridden by ActsAsTenant gem](https://github.com/ErwinM/acts_as_tenant/blob/master/lib/acts_as_tenant/model_extensions.rb#L72-L85). Then after I cast existing record on form I have an issue with tracking this overridden attribute. It shown like changed (`{ "market_id" => [nil, 1] }`) but no changes happened on it at all. I think it happens because of this desynchronization between real database and model changes and form changes. 
So my …
=> Add `mutations_from_database` copy to `ActiveType.cast`

.github/workflows/test.yml
=> use mariadb-client instead of mysql-client in tests

lib/active_type/virtual_attributes.rb
This fixes the following ruby warning:
```
lib/active_type/virtual_attributes.rb:115:warning: character class has duplicated range: /\A[A-z0-9_]*\z/
```
This fix adapts the regex in a way that does not alter its matching pattern. However, while the pattern `[A-z]` includes all the characters from the alphabet, lower and upper case, it also includes the characters `[`, `\`, `]`, and `^` (among `_`, which is the point of this issue). If this is not desired, the pattern should be changed to `/\A[A-Za-z0-9_]*\z/` instead, as it would be more specific and does not allow any additional characters.
Thanks for considering this PR 👍
=> Fix a ruby warning due to redundant regex pattern

lib/active_type/virtual_attributes.rb
In `lib/active_type/virtual_attributes.rb`, an alias is created so that the original ActiveRecord method `attribute` still can be used:
```ruby
class << self
if method_defined?(:attribute)
alias_method :ar_attribute, :attribute
end
end
```
The problem is that, since this is an `ActiveSupport::Concern`, the `ClassMethods`-Module which contains the new `attribute` method is mixed in **before** the aliassing happens. This effectively aliases the ActiveType `attribute` to itself - at least with Ruby 3 and Rails 7.
This PR attempts to fix this by renaming the overriding method `attribute` to `at_attribute` and performing a second alias operation.
Many thanks for having a look at this 👍 🎆
=> Fix aliassing ar_attribute method

lib/active_type/virtual_attributes.rb
Fix an error when an attribute name is a keyword, e.g. `alias`, `end`, …
Given
```ruby
attribute :alias, :string
```
I got an error
```
SyntaxError:
active_type-2.2.0/lib/active_type/virtual_attributes.rb:103: syntax error, unexpected '[', expecting `end'
...ias != virtual_attributes_were["alias"]
```
The patch adds a prefix `self` that fixes the syntax error in generated code.
```ruby
self.alias != virtual_attributes_were["alias"]
```
=> Support attributes that are also a keyword

CHANGELOG.md, Gemfile.5.2.mysql2.lock, Gemfile.5.2.pg.lock, Gemfile.5.2.sqlite3.lock, Gemfile.6.0.sqlite3.lock, Gemfile.6.1.pg.lock, Gemfile.6.1.sqlite3.lock, Gemfile.7.0.pg.lock, Gemfile.7.0.sqlite3.lock, README.md, lib/active_type/util.rb, lib/active_type/util/active_record.rb, lib/active_type/version.rb, spec/active_type/util_spec.rb
=> #after_cast

lib/active_type/virtual_attributes.rb, spec/active_type/object_spec.rb, spec/active_type/record_spec.rb, spec/shared_examples/belongs_to.rb, spec/shared_examples/dirty_tracking.rb
`belongs_to` associations in `ActiveType::Object` did not properly validate presence when `ActiveRecord::Base.belongs_to_required_by_default = true` and `ActiveRecord.belongs_to_required_validates_foreign_key = false` (Rails default).
```ruby
require "bundler/inline"
gemfile do
source "https://rubygems.org"
gem "activerecord"
gem "sqlite3"
gem "active_type"
end
require "active_record"
require "sqlite3"
require "active_type"
ActiveRecord::Base.belongs_to_required_by_default = true
ActiveRecord.belongs_to_required_validates_foreign_key = false
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
create_table :shops do |t|
end
create_table :items do |t|
t.references :shop, null: false, foreign_key: true
end
end
class Shop < …
```
=> Fix `belongs_to` association validation for virtual attributes
